### ISSUE TITLE
MacOS: optimized (AVX2) implementation does not compile

### ISSUE THREAD

**Issue by mouse07410** [newhopecrypto/newhope#1]
See https://github.com/newhopecrypto/newhope-usenix/issues/1 - same symptom:
```
. . . . .
ntt_double.s:4538:1: error: 32-bit absolute addressing is not supported in 64-bit mode
vmovdqu qinv_vector,%ymm1
^
make: *** [PQCgenKAT_kem] Error 1
```

Here's the advice YASM assembler gives:
```
. . . . .
ntt_double.s:4538: error: macho: sorry, cannot apply 32 bit absolute relocations in 64 bit mode, consider "[_symbol wrt rip]" for mem access, "qword" and "dq _foo" for pointers.
```

**Comment by mouse07410** [comment]
@cryptojedi can I hope that you'd help with this issue?

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
> @cryptojedi can I hope that you'd help with this issue?

Working on it. The problems you reported are easily fixed, but there
seem to be more issues under OSX and I don't have a system to test on.

**Comment by mouse07410** [comment]
> Working on it

Excellent - I'm glad to hear this.

> The problems you reported are easily fixed, but there
seem to be more issues under OSX and I don't have a system to test on.

@cryptojedi I realize that some platforms are not as common as others. I'll be happy to test for you whatever experiment or change you may need to validate. My platform is MacOS Mojave 10.14.1 (and High Sierra 10.13.6) with Xcode-10.1, plus Macports-installed Clang-7.0, GCC-8, and YASM-1.3.0 and NASM-2.14 assemblers (in addition to the one provided by Xcode). 

Here are some CPUs I can test your changes on (reported via `botan cpuid`):
```
CPUID flags: sse2 ssse3 sse41 sse42 avx2 avx512f rdtsc bmi1 bmi2 adx aes_ni clmul rdrand rdseed
CPUID flags: sse2 ssse3 sse41 sse42 avx2 rdtsc bmi1 bmi2 adx aes_ni clmul rdrand rdseed
CPUID flags: sse2 ssse3 sse41 sse42 avx2 rdtsc bmi1 bmi2 aes_ni clmul rdrand
```

**Comment by mouse07410** [comment]
~~Could you apply the same fix (https://github.com/newhopecrypto/newhope-usenix/issues/1) here please?~~ *It compiles fine on MacOS with the latest Xcode.*

Also, is there a difference in the actual code between this repo and https://github.com/newhopecrypto/newhope.git?

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:



> Could you apply the same fix
> (https://github.com/newhopecrypto/newhope-usenix/issues/1) here
> please?

Now I'm confused; this should be fixed in newhope-usenix. What's the
remaining issue?

> Also, is there a difference in the actual code between this repo and
> https://github.com/newhopecrypto/newhope.git?

Yes, there are multiple differences between the USENIX version of
NewHope and the NIST Submission NewHope. Most importantly:

- NewHope as submitted to NIST has a CCA-secure version while
  NewHope-USENIX is only CPA secure

- The CCA transform demands a lower failure probability, so we use a a
  paramter k=8 instead of k=16 in the centered binomial noise
  distribution. 

- Sampling of the public polynomial 'a' is now supporting parallel
  vectorized calls to SHAKE.

For more details, please see the NIST specification document:
https://newhopecrypto.org/data/NewHope_2018_12_02.pdf

**Comment by mouse07410** [comment]
> this should be fixed in newhope-usenix. What's the remaining issue?

No, no remaining issues. I was mistaken - avx2 in the .zip file from the NIST site does not compile on MacOS, but avx2 from this repo compiles and runs fine. Thank you!

An unrelated question. NewHope was originally designed as a Key Agreement protocol, later adopted for KEM as per NIST submission requirement, correct? I basically need a Key Agreement rather than Key Transport (when one party essentially tells the other what their shared key will be). Could you show how I can use the existing code from this repo to implement a Key Agreement?

Thanks!

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
> > this should be fixed in newhope-usenix. What's the
> remaining issue?
> 
> No, no remaining issues. I was mistaken - avx2 in the .zip file from
> the NIST site does not compile on MacOS, but avx2 from this repo
> compiles and runs fine. Thank you!

All right, great!

> An unrelated question. NewHope was originally designed as a Key
> Agreement protocol, later adopted for KEM as per NIST submission
> requirement, correct? I basically need a Key Agreement rather than Key
> Transport. Could you show how I can use the existing code from this
> repo to implement a Key Agreement?

I'm not exactly sure what you mean here. If you want a contributory KEM,
i.e., a KEM in which neither party can choose the final session key,
then the CCA-secure variant of NewHope as submitted to NIST will be just
fine: the public key of Alice gets hashed into the "pre-key" K, see line
4 of Algorithm 20 in
https://newhopecrypto.org/data/NewHope_2018_12_02.pdf.

**Comment by mouse07410** [comment]
> If you want a contributory KEM, i.e., a KEM in which neither party can choose the final session key...

Basically, yes. 

And ideally, something with HMQV flavor, where the parties are implicitly authenticated - but that's a different story.

> ...then the CCA-secure variant of NewHope as submitted to NIST will be just
fine: the public key of Alice gets hashed into the "pre-key" K, see line
4 of Algorithm 20...

Thanks - let me check that algorithm, and get back to you.

**Comment by mouse07410** [comment]
@cryptojedi I checked it, and unless I'm missing something, that doesn't seem sufficient. Even though Alice (or Bob) in the above example is not expected to be able to invert the hash, she could (after spending huge amount of computing time) find a peculiar public key that hashes to what she'd want. Not a common or an easy attack, but still a concern.

Compare this approach to a classic KEX, like EDH/ECEDH - in order to fudge the result, Bob would have to come up with the right g^y *in real time*, because he cannot know in advance what kind of g^x would be thrown at him. In other words, with KEX as long as at least one party is "good" ("honest", not subverted, etc.) the resulting shared key is "good". I don't think this property holds for KEM, does it?

I agree that contributory KEM is better than a traditional Key Transport, but I'd like better assurance that neither party can have too much influence over the final key.

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
> @cryptojedi I checked it, and unless I'm missing something, that
> doesn't seem sufficient. Even though Alice (or Bob) in the above
> example is not expected to be able to invert the hash, she could
> (after spending huge amount of computing time) find a peculiar public
> key that hashes to what she'd want. Not a common or an easy attack,
> but still a concern.

It really shouldn't be; if you assume an attacker who can compute hash
preimages, you have much bigger problems.

> Compare this approach to a classic KEX, like EDH/ECEDH - in order to
> fudge the result, Bob would have to come up with the right g^y *in
> real time*, because he cannot know in advance what kind of g^x would
> be thrown at him. In other words, with KEX as long as at least one
> party is "good" ("honest", not subverted, etc.) the resulting shared
> key is "good". I don't think this property holds for KEM, does it?

Indeed, what you're pointing to is the difference between a
non-interactive key exchange (NIKE) and a KEM. No KEM would be able to
resist the "attack" you're describing. The only post-quantum NIKE that
can be considered practical is CSIDH: https://csidh.isogeny.org.

> I agree that contributory KEM is better than a traditional Key
> Transport, but I'd like better assurance that neither party can have
> too much influence over the final key.

What protocol are you considering where such an influence would be a
problem? Are you concerned about covert channels?

**Comment by mouse07410** [comment]
> It really shouldn't be; if you assume an attacker who can compute hash preimages, you have much bigger problems.

No, it's not about the attacker being able to compute pre-images - it's about the attacker willing to invest significant time to search for a something that would hash into something "close enough". As an example of what's possible - think BitCoin mining.

Another possibility - the attacker compromises RNG on, e.g., Alice's computer, so it produces, e.g., only 2^16 different values. What I'm driving at - when one party has complete control over the outcome, there's a problem (for me).

> Indeed, what you're pointing to is the difference between a non-interactive key exchange (NIKE) and a KEM. No KEM would be able to resist the "attack" you're describing.

Which is why I'm trying to find/build a KEX (NIKE) from the given primitives. ;-)

> The only post-quantum NIKE that can be considered practical is CSIDH

Am I correct that it has great (aka small enough ;) key sizes, but is extremely slow?

> Are you concerned about covert channels?

Yes I am (among other things).

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
> > It really shouldn't be; if you assume an attacker who can compute hash preimages, you have much bigger problems.
> 
> No, it's not about the attacker being able to compute pre-images -
> it's about the attacker willing to invest significant time to search
> for a something that would hash into something "close enough". As an
> example of what's possible - think BitCoin mining.
> 
> Another possibility - the attacker compromises RNG on, e.g., Alice's
> computer, so it produces, e.g., only 2^16 different values. What I'm
> driving at - when one party has complete control over the outcome,
> there's a problem (for me).

A broken RNG on either side is also a problem for classical (EC)DH. 

> > Indeed, what you're pointing to is the difference between a non-interactive key exchange (NIKE) and a KEM. No KEM would be able to resist the "attack" you're describing.
> 
> Which is why I'm trying to find/build a KEX (NIKE) from the given primitives. ;-)

It makes sense to say "NIKE", because KEX means different thing to
different people. For example, the "Ding Key Exchange" submitted to NIST
or also the original (USENIX) NewHope are just passively secure KEMs.

> > The only post-quantum NIKE that can be considered practical is CSIDH
> 
> Am I correct that it has great (aka small enough ;) key sizes, but is extremely slow?

That depends on your definition of "extremely slow". It is much slower
than, say, lattice-based KEMs, but you can do a key exchange in less
than a second on large CPUs.

In principle you can also do a NIKE using lattices, see
https://crypto.stackexchange.com/questions/48146/converting-newhope-lwe-key-exchange-to-a-diffe-hellman-like-algorithm/
Note that in order to force users to choose noise from the right
distribution, you need to attach zero-knowledge proofs to the public
key.

**Comment by mouse07410** [comment]
> A broken RNG on either side is also a problem for classical (EC)DH

You have a point here.

>  The only post-quantum NIKE that can be considered practical is CSIDH ... It is much slower
than, say, lattice-based KEMs, but you can do a key exchange in less than a second on large CPUs...

**Thank you!** You gave me **excellent** pointers, and I'm now following them.

BTW, optimized CSIDH on a good modern/recent Intel Core i7 completed in about 240ms for p503, but took 1,300ms for p1024 (this was unoptimized code - pure C). We'll see if it can be improved.

> In principle you can also do a NIKE using lattices, see
https://crypto.stackexchange.com/questions/48146/converting-newhope-lwe-key-exchange-to-a-diffe-hellman-like-algorithm/

And that page says:
> ...achieving similar security as regular Ring-LWE encryption / key exchange schemes would result in keys that are around 20 - 40 times larger than in Ring-LWE based schemes. So something around 20KB - 40KB could be expected...

What is your estimate on the performance/time this NIKE-from-NewHope would require? Also 20-40 times longer...?

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
 
> BTW, optimized CSIDH on a good modern/recent Intel Core i7 completed
> in about 240ms for p503, but took 1,300ms for p1024 (this was
> unoptimized code - pure C). We'll see if it can be improved.

Be careful with the code that's online, it's heavily non-constant-time
and thus vulnerable to timing attacks. At Asiacrypt the authors
mentioned that they do also have constant-time code, which is about 6x
slower.

**Comment by mouse07410** [comment]
> Be careful with the code that's online, it's heavily non-constant-time
and thus vulnerable to timing attacks

Thank you, very good to know.

*It so happens, that one particular application I have in mind is not a subject to timing attacks. But in general it pays to be aware.*

> they do also have constant-time code, which is about 6x slower.

Being 6x slower than, say, 1.3 seconds would not be acceptable.

Any guesstimate on the expected performance of NewHope-based NIKE (with keys being 20-40 times larger)? And that was (if I understood that stackexchange post correctly) a *non-*authenticated KEX, so authenticating it would cost extra, right?

**Comment by cryptojedi** [comment]
Mouse <notifications@github.com> wrote:
 
> Any guesstimate on the expected performance of NewHope-based NIKE
> (with keys being 20-40 times larger)? 

As far as I know, the best (only?) concrete analysis is in the Master's
thesis by Bor de Kock: 
https://pure.tue.nl/ws/portalfiles/portal/109115854/CSE643_BordeKock_thesis_FINAL.pdf

Beware though, that the scheme described in this thesis does not include
the zero-knowledge proof that would be required to achieve security
notions commonly considered for NIKEs (see, e.g.,
https://eprint.iacr.org/2012/732.pdf). My understanding is that this ZKP
would be the most costly part (in terms of size at least).

> And that was (if I understood that stackexchange post correctly) a
> *non-*authenticated KEX, so authenticating it would cost extra, right?

Yes, you'd need to combine static and ephemeral key exchanges for that.
